"""
Veridi Logistics — "Last Mile" Delivery Audit Dashboard
AmaliTech Data Engineering Challenge — Project 1
Run: streamlit run project1_dashboard.py
Requires: master_clean.csv, state_stats.csv, seller_stats.csv
          (generated by the notebook olist_logistics_auditor.ipynb)
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings("ignore")

# ── Page config ──────────────────────────────────────────────
st.set_page_config(
    page_title="Veridi Logistics Audit",
    page_icon="🚚",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Custom CSS ────────────────────────────────────────────────
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;600;700&family=DM+Mono&display=swap');
    html, body, [class*="css"] { font-family: 'Space Grotesk', sans-serif; }
    .main { background: #0f1117; }
    .metric-card {
        background: linear-gradient(135deg, #1a1d2e, #252840);
        border: 1px solid #3a3d5c;
        border-radius: 12px;
        padding: 20px;
        text-align: center;
    }
    .metric-value { font-size: 2.2rem; font-weight: 700; }
    .metric-label { font-size: 0.85rem; color: #8b8fa8; margin-top: 4px; }
    .insight-box {
        background: linear-gradient(135deg, #1c2b1a, #1a2e20);
        border-left: 4px solid #2ecc71;
        border-radius: 8px;
        padding: 16px 20px;
        margin: 12px 0;
    }
    .warning-box {
        background: linear-gradient(135deg, #2b1a1a, #2e1a1a);
        border-left: 4px solid #e74c3c;
        border-radius: 8px;
        padding: 16px 20px;
        margin: 12px 0;
    }
    h1, h2, h3 { color: #e8eaf6; }
</style>
""", unsafe_allow_html=True)

# ── Load Data ─────────────────────────────────────────────────
@st.cache_data
def load_data():
    master = pd.read_csv("master_clean.csv", parse_dates=[
        "order_purchase_timestamp",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ])
    state_stats  = pd.read_csv("state_stats.csv")
    seller_stats = pd.read_csv("seller_stats.csv")
    return master, state_stats, seller_stats

try:
    master, state_stats, seller_stats = load_data()
    DATA_LOADED = True
except FileNotFoundError:
    DATA_LOADED = False

# ── Header ────────────────────────────────────────────────────
st.markdown("# 🚚 Veridi Logistics — Last Mile Delivery Audit")
st.markdown("**AmaliTech Data Engineering Challenge** | Olist Brazilian E-Commerce Dataset")
st.divider()

if not DATA_LOADED:
    st.error("""
    **CSV files not found.**  
    Please run the notebook `olist_logistics_auditor.ipynb` first to generate:
    - `master_clean.csv`
    - `state_stats.csv`  
    - `seller_stats.csv`
    
    Then place all files in the same folder as this dashboard script.
    """)
    st.stop()

# ── Sidebar Filters ───────────────────────────────────────────
st.sidebar.image("https://img.icons8.com/fluency/96/delivery.png", width=60)
st.sidebar.markdown("## 🎛️ Filters")

all_states = sorted(master["customer_state"].dropna().unique())
selected_states = st.sidebar.multiselect(
    "Filter by State", all_states, default=all_states,
    help="Select one or more Brazilian states"
)

all_statuses = ["On Time", "Late", "Super Late"]
selected_statuses = st.sidebar.multiselect(
    "Delivery Status", all_statuses, default=all_statuses
)

all_categories = sorted(master["category_en"].dropna().unique())
selected_categories = st.sidebar.multiselect(
    "Product Category", all_categories, default=all_categories
)

st.sidebar.divider()
st.sidebar.markdown("### 📊 About")
st.sidebar.info(
    "This dashboard audits Veridi Logistics' last-mile delivery performance, "
    "correlating delivery delays with customer review scores across Brazil."
)

# ── Apply Filters ─────────────────────────────────────────────
filtered = master[
    master["customer_state"].isin(selected_states) &
    master["delivery_status"].isin(selected_statuses) &
    master["category_en"].isin(selected_categories)
].copy()

# ── KPI Row ───────────────────────────────────────────────────
st.markdown("### 📈 Key Performance Indicators")
col1, col2, col3, col4, col5 = st.columns(5)

total       = len(filtered)
on_time_pct = (filtered["delivery_status"] == "On Time").mean() * 100
late_pct    = (filtered["is_late"]).mean() * 100
super_pct   = (filtered["delivery_status"] == "Super Late").mean() * 100
avg_review  = filtered["review_score"].mean()

def kpi(col, value, label, color="#a0c4ff"):
    col.markdown(f"""
    <div class="metric-card">
        <div class="metric-value" style="color:{color}">{value}</div>
        <div class="metric-label">{label}</div>
    </div>""", unsafe_allow_html=True)

kpi(col1, f"{total:,}",           "Total Orders Analyzed",  "#a0c4ff")
kpi(col2, f"{on_time_pct:.1f}%",  "On Time Rate",           "#2ecc71")
kpi(col3, f"{late_pct:.1f}%",     "Late Delivery Rate",     "#f39c12")
kpi(col4, f"{super_pct:.1f}%",    "Super Late (>5 days)",   "#e74c3c")
kpi(col5, f"{avg_review:.2f}/5",  "Avg Review Score",       "#f8d56b")

st.markdown("<br>", unsafe_allow_html=True)

# ── Row 1: Delivery Status + Delay Distribution ───────────────
st.markdown("### 📦 Delivery Performance Overview")
r1c1, r1c2 = st.columns(2)

with r1c1:
    status_counts = filtered["delivery_status"].value_counts()
    color_map = {"On Time": "#2ecc71", "Late": "#f39c12", "Super Late": "#e74c3c"}
    fig_pie = px.pie(
        values=status_counts.values,
        names=status_counts.index,
        color=status_counts.index,
        color_discrete_map=color_map,
        title="Delivery Status Breakdown",
        hole=0.45
    )
    fig_pie.update_traces(textinfo="percent+label")
    fig_pie.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6",
        showlegend=False
    )
    st.plotly_chart(fig_pie, use_container_width=True)

with r1c2:
    fig_hist = px.histogram(
        filtered,
        x="Days_Difference",
        nbins=60,
        color="delivery_status",
        color_discrete_map=color_map,
        title="Distribution of Delivery Delay (Days)",
        labels={"Days_Difference": "Days Difference (+ = Early, − = Late)"},
        range_x=[-30, 30]
    )
    fig_hist.add_vline(x=0, line_dash="dash", line_color="white", annotation_text="On-Time Threshold")
    fig_hist.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6",
        barmode="overlay"
    )
    st.plotly_chart(fig_hist, use_container_width=True)

# ── Row 2: Geographic Analysis ────────────────────────────────
st.markdown("### 🗺️ Geographic Analysis — Late Deliveries by State")

state_filtered = state_stats[state_stats["customer_state"].isin(selected_states)].sort_values("late_pct", ascending=False)

r2c1, r2c2 = st.columns([2, 1])

with r2c1:
    fig_bar = px.bar(
        state_filtered,
        x="customer_state", y="late_pct",
        color="late_pct",
        color_continuous_scale="RdYlGn_r",
        title="% Late Deliveries by Brazilian State",
        labels={"customer_state": "State", "late_pct": "% Late"},
        text="late_pct",
        hover_data=["total_orders", "avg_review"]
    )
    fig_bar.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
    fig_bar.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6",
        coloraxis_showscale=False,
        height=400
    )
    st.plotly_chart(fig_bar, use_container_width=True)

with r2c2:
    st.markdown("#### 🏆 State Rankings")
    top5 = state_filtered.head(5)[["customer_state", "late_pct", "avg_review"]].reset_index(drop=True)
    top5.columns = ["State", "Late %", "Avg Review"]
    top5["Late %"] = top5["Late %"].map("{:.1f}%".format)
    top5["Avg Review"] = top5["Avg Review"].map("{:.2f}".format)
    st.markdown("**🔴 Worst Performing States**")
    st.dataframe(top5, use_container_width=True, hide_index=True)

    best5 = state_filtered.tail(5)[["customer_state", "late_pct", "avg_review"]].reset_index(drop=True)
    best5.columns = ["State", "Late %", "Avg Review"]
    best5["Late %"] = best5["Late %"].map("{:.1f}%".format)
    best5["Avg Review"] = best5["Avg Review"].map("{:.2f}".format)
    st.markdown("**🟢 Best Performing States**")
    st.dataframe(best5, use_container_width=True, hide_index=True)

# ── Row 3: Sentiment Correlation ──────────────────────────────
st.markdown("### 💬 Sentiment Correlation — Late Deliveries vs Review Scores")
r3c1, r3c2 = st.columns(2)

with r3c1:
    sent = (
        filtered.groupby("delivery_status")["review_score"]
        .mean()
        .reindex(["On Time", "Late", "Super Late"])
        .reset_index()
    )
    sent.columns = ["Status", "Avg Review Score"]
    fig_sent = px.bar(
        sent, x="Status", y="Avg Review Score",
        color="Status",
        color_discrete_map=color_map,
        title="Avg Review Score by Delivery Status",
        text="Avg Review Score",
        range_y=[0, 5.5]
    )
    fig_sent.update_traces(texttemplate="%{text:.2f}", textposition="outside")
    fig_sent.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6",
        showlegend=False
    )
    st.plotly_chart(fig_sent, use_container_width=True)

with r3c2:
    sample = filtered[filtered["review_score"].notna()].sample(min(3000, len(filtered)), random_state=42)
    fig_scatter = px.scatter(
        sample,
        x="Days_Difference", y="review_score",
        color="delivery_status",
        color_discrete_map=color_map,
        opacity=0.4,
        title="Delay vs Review Score (sampled)",
        labels={"Days_Difference": "Days Difference", "review_score": "Review Score"},
        trendline="ols"
    )
    fig_scatter.add_vline(x=0, line_dash="dash", line_color="white")
    fig_scatter.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6"
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

# ── Row 4: Seller Risk (Candidate's Choice) ───────────────────
st.markdown("### 🎯 Candidate's Choice: Seller Risk Score Matrix")
st.markdown(
    "_Identifying high-risk sellers who consistently over-promise delivery dates, "
    "enabling targeted intervention rather than system-wide logistics overhaul._"
)

r4c1, r4c2 = st.columns([3, 1])

with r4c1:
    tier_colors = {"Low Risk": "#2ecc71", "Medium Risk": "#f39c12", "High Risk": "#e74c3c"}
    fig_risk = px.scatter(
        seller_stats,
        x="late_pct", y="avg_review",
        color="risk_tier",
        color_discrete_map=tier_colors,
        size="total_orders",
        hover_data=["seller_id", "total_orders", "risk_score", "super_late_pct"],
        title="Seller Risk Matrix: Late Rate vs Customer Review Score",
        labels={"late_pct": "% Late Deliveries", "avg_review": "Avg Review Score", "risk_tier": "Risk"}
    )
    fig_risk.add_hline(y=4, line_dash="dash", line_color="gray")
    fig_risk.add_vline(x=20, line_dash="dash", line_color="gray")
    fig_risk.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6",
        height=450
    )
    st.plotly_chart(fig_risk, use_container_width=True)

with r4c2:
    st.markdown("#### ⚠️ High Risk Sellers")
    high_risk = seller_stats[seller_stats["risk_tier"] == "High Risk"].nlargest(8, "risk_score")
    st.dataframe(
        high_risk[["seller_id", "total_orders", "risk_score"]]
        .rename(columns={"seller_id": "Seller", "total_orders": "Orders", "risk_score": "Risk Score"})
        .reset_index(drop=True),
        use_container_width=True, hide_index=True
    )
    risk_dist = seller_stats["risk_tier"].value_counts()
    st.metric("High Risk Sellers",   int(risk_dist.get("High Risk", 0)))
    st.metric("Medium Risk Sellers", int(risk_dist.get("Medium Risk", 0)))
    st.metric("Low Risk Sellers",    int(risk_dist.get("Low Risk", 0)))

# ── Key Insights Box ──────────────────────────────────────────
st.divider()
st.markdown("### 💡 Executive Insights")

worst_s = state_stats.sort_values("late_pct", ascending=False).iloc[0]
best_s  = state_stats.sort_values("late_pct").iloc[0]

late_total = (master["is_late"]).mean() * 100
score_ontime = master[master["delivery_status"] == "On Time"]["review_score"].mean()
score_late   = master[master["delivery_status"] == "Super Late"]["review_score"].mean()

col_a, col_b = st.columns(2)
with col_a:
    st.markdown(f"""
    <div class="warning-box">
    <b>🔴 Critical Finding</b><br><br>
    <b>{late_total:.1f}%</b> of all delivered orders arrived later than the estimated date.
    The worst state is <b>{worst_s['customer_state']}</b> with <b>{worst_s['late_pct']:.1f}%</b> late rate —
    compared to the best, <b>{best_s['customer_state']}</b> at only <b>{best_s['late_pct']:.1f}%</b>.
    This confirms the CEO's suspicion: the problem is <b>real and regional</b>.
    </div>
    """, unsafe_allow_html=True)

with col_b:
    st.markdown(f"""
    <div class="insight-box">
    <b>🟢 Proven Link: Delays → Bad Reviews</b><br><br>
    On-time customers give an average score of <b>{score_ontime:.2f}/5</b>,
    while Super Late customers give only <b>{score_late:.2f}/5</b>.
    This is a drop of <b>{score_ontime - score_late:.2f} stars</b> —
    statistically significant proof that logistics performance directly drives 
    customer satisfaction and brand reputation.
    </div>
    """, unsafe_allow_html=True)

st.markdown("---")
st.markdown(
    "<center><small>Veridi Logistics Audit Dashboard · Built with Streamlit & Plotly · "
    "AmaliTech Data Engineering Challenge</small></center>",
    unsafe_allow_html=True
)
