# -*- coding: utf-8 -*-
"""project2_sugar_trap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w23DT2cL27kSYMv3fzMUdkAoYgJjbe23

# 🥗 The "Sugar Trap" — Market Gap Analysis
**AmaliTech Data Engineering Challenge — Project 2**

**Client:** Helix CPG Partners  
**Dataset:** [Open Food Facts](https://world.openfoodfacts.org/data)

---
### Notebook Structure
- **Section 0:** Setup & Data Loading
- **Story 1:** Data Ingestion & Cleaning
- **Story 2:** Category Wrangler — High-Level Buckets
- **Story 3:** Nutrient Matrix Visualization
- **Story 4:** Market Gap Recommendation
- **Bonus:** Hidden Gem — Protein Source Ingredients
- **Candidate's Choice:** Nutrition Score vs Market Position
---

## Section 0: Setup & Data Loading
"""

!pip install plotly wordcloud --quiet
print('✅ Libraries ready')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import re
from collections import Counter
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)
plt.style.use('seaborn-v0_8-whitegrid')
print('✅ Imports done')

# ─────────────────────────────────────────────────────────────
# Download Open Food Facts dataset
# Full file is 3GB+ — we load only the first 500,000 rows
# ─────────────────────────────────────────────────────────────
import os

DATA_FILE = 'en.openfoodfacts.org.products.csv'

# Check if already downloaded
if not os.path.exists(DATA_FILE):
    print('Downloading Open Food Facts dataset...')
    print('This may take a few minutes (~500MB download).')
    import urllib.request
    url = 'https://static.openfoodfacts.org/data/en.openfoodfacts.org.products.csv.gz'
    urllib.request.urlretrieve(url, 'openfoodfacts.csv.gz')
    print('✅ Downloaded. Now loading first 500k rows...')
else:
    print(f'✅ Found {DATA_FILE} locally')

# ─────────────────────────────────────────────────────────────
# Load only needed columns from the first 500,000 rows
# This avoids memory issues with the 3GB+ full dataset
# ─────────────────────────────────────────────────────────────
COLS_NEEDED = [
    'product_name',
    'categories_tags',
    'ingredients_text',
    'sugars_100g',
    'proteins_100g',
    'fat_100g',
    'fiber_100g',
    'energy_100g',
    'nutrition_grade_fr',
    'nutriscore_score',
    'countries_tags',
    'brands'
]

# Try .gz first (downloaded compressed), fall back to .csv
try:
    raw = pd.read_csv(
        'openfoodfacts.csv.gz',
        sep='\t',
        usecols=lambda c: c in COLS_NEEDED,
        nrows=500_000,
        low_memory=False,
        on_bad_lines='skip'
    )
    print('Loaded from .gz')
except Exception:
    raw = pd.read_csv(
        DATA_FILE,
        sep='\t',
        usecols=lambda c: c in COLS_NEEDED,
        nrows=500_000,
        low_memory=False,
        on_bad_lines='skip'
    )
    print('Loaded from .csv')

print(f'Shape: {raw.shape}')
display(raw.head(3))

"""---
## Story 1: Data Ingestion & "The Clean Up" 🧹
**Goal:** Remove products with erroneous or missing nutritional data.

**Cleaning Strategy:**
1. Drop rows missing `product_name`, `sugars_100g`, or `proteins_100g`
2. Remove biologically impossible values (values >100g per 100g)
3. Remove extreme outliers (>3 standard deviations)
4. Keep only snack-relevant products (filter by categories_tags)
"""

# ─────────────────────────────────────────────────────────────
# Step 1a: Missing value analysis
# ─────────────────────────────────────────────────────────────
print('=== Missing Value Summary ===')
missing = raw.isnull().sum().sort_values(ascending=False)
missing_pct = (missing / len(raw) * 100).round(1)
print(pd.DataFrame({'Missing': missing, 'Pct': missing_pct}))

print(f'\nRaw rows: {len(raw):,}')

# ─────────────────────────────────────────────────────────────
# Step 1b: Drop essential nulls
# ─────────────────────────────────────────────────────────────
df = raw.copy()

# Drop rows with missing required fields
df = df.dropna(subset=['product_name', 'sugars_100g', 'proteins_100g'])
print(f'After dropping missing essentials: {len(df):,}')

# Drop rows with empty product_name
df = df[df['product_name'].str.strip().str.len() > 0]
print(f'After removing blank product names: {len(df):,}')

# Ensure numeric types
numeric_cols = ['sugars_100g', 'proteins_100g', 'fat_100g', 'fiber_100g', 'energy_100g']
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# ─────────────────────────────────────────────────────────────
# Step 1c: Remove biologically impossible values
# Per 100g: sugars + proteins + fat + fiber cannot exceed 100g
# ─────────────────────────────────────────────────────────────

# Hard limits: no nutrient can be > 100g per 100g of product
df = df[
    (df['sugars_100g'].between(0, 100)) &
    (df['proteins_100g'].between(0, 100)) &
    (df['fat_100g'].fillna(0).between(0, 100))
]
print(f'After impossible value filter: {len(df):,}')

# Soft outlier filter: remove extreme z-scores (>4 std) for sugar & protein
for col in ['sugars_100g', 'proteins_100g']:
    mean, std = df[col].mean(), df[col].std()
    df = df[np.abs(df[col] - mean) <= 4 * std]

print(f'After z-score outlier removal:   {len(df):,}')
print(f'\nRows removed total: {len(raw) - len(df):,} ({(1 - len(df)/len(raw))*100:.1f}%)')

print('\n=== Cleaned Data Stats ===')
display(df[['sugars_100g', 'proteins_100g', 'fat_100g', 'fiber_100g']].describe().round(2))

"""---
## Story 2: The Category Wrangler 📂
**Goal:** Parse messy `categories_tags` and assign readable high-level categories.

**5 Primary Categories:**
1. Chocolate & Candy
2. Chips & Savoury Snacks
3. Protein & Health Bars
4. Biscuits & Cookies
5. Cereals & Granola
6. Dairy & Yogurt
7. Other Snacks
"""

# ─────────────────────────────────────────────────────────────
# Step 2a: Parse categories_tags
# Example: "en:snacks,en:sweet-snacks,en:chocolate" → list
# ─────────────────────────────────────────────────────────────
def clean_tag(tag):
    """Remove language prefix and clean tag"""
    tag = str(tag).lower().strip()
    tag = re.sub(r'^[a-z]{2}:', '', tag)  # remove en: fr: etc.
    tag = tag.replace('-', ' ').replace('_', ' ')
    return tag

def parse_categories(cat_string):
    """Parse comma-separated categories string into a list"""
    if pd.isna(cat_string) or str(cat_string).strip() == '':
        return []
    return [clean_tag(t) for t in str(cat_string).split(',')]

df['categories_list'] = df['categories_tags'].apply(parse_categories)
df['categories_str']  = df['categories_list'].apply(lambda x: ' '.join(x))

# Show most common tags
all_tags = [tag for tags in df['categories_list'] for tag in tags]
print('Top 20 most common category tags:')
display(pd.Series(Counter(all_tags)).nlargest(20))

# ─────────────────────────────────────────────────────────────
# Step 2b: Assign Primary Category via keyword matching
# Priority order matters — first match wins
# ─────────────────────────────────────────────────────────────
CATEGORY_RULES = [
    ('Protein & Health Bars', ['protein bar', 'protein bar', 'energy bar', 'health bar',
                                'nut bar', 'cereal bar', 'sport', 'fitness']),
    ('Chocolate & Candy',     ['chocolate', 'candy', 'confectionery', 'caramel',
                                'gummy', 'marshmallow', 'toffee', 'fudge', 'truffle']),
    ('Chips & Savoury Snacks',['chips', 'crisps', 'popcorn', 'pretzel', 'cracker',
                                'savoury snack', 'savory snack', 'pork rind', 'tortilla']),
    ('Biscuits & Cookies',    ['biscuit', 'cookie', 'wafer', 'shortbread', 'digestive']),
    ('Cereals & Granola',     ['cereal', 'granola', 'muesli', 'oat', 'porridge', 'breakfast']),
    ('Dairy & Yogurt',        ['yogurt', 'yoghurt', 'dairy', 'cheese snack', 'milk snack']),
    ('Nuts & Seeds',          ['nut', 'almond', 'cashew', 'peanut', 'seed', 'trail mix',
                                'pistachio', 'walnut', 'sunflower']),
    ('Dried Fruit & Fruit Snacks', ['dried fruit', 'fruit snack', 'raisin', 'apricot',
                                     'fig', 'date', 'fruit bar', 'fruit leather']),
]

def assign_category(cat_str):
    for category, keywords in CATEGORY_RULES:
        if any(kw in cat_str for kw in keywords):
            return category
    return 'Other Snacks'

df['primary_category'] = df['categories_str'].apply(assign_category)

print('=== Primary Category Distribution ===')
cat_dist = df['primary_category'].value_counts()
display(cat_dist)

# Keep snack-relevant products (drop if 'Other Snacks' and no snack tag)
snack_keywords = ['snack', 'sweet', 'treat', 'dessert', 'confection']
is_snack = df['categories_str'].apply(lambda x: any(k in x for k in snack_keywords))
df = df[is_snack | (df['primary_category'] != 'Other Snacks')].copy()

print(f'\nFinal dataset after snack filter: {len(df):,} products')

# ─────────────────────────────────────────────────────────────
# Story 2 Chart: Category distribution
# ─────────────────────────────────────────────────────────────
cat_counts = df['primary_category'].value_counts().reset_index()
cat_counts.columns = ['Category', 'Count']

fig = px.bar(
    cat_counts, x='Count', y='Category',
    orientation='h',
    color='Count',
    color_continuous_scale='Viridis',
    title='🍫 Product Count by Category',
    text='Count'
)
fig.update_traces(textposition='outside')
fig.update_layout(height=450, coloraxis_showscale=False, yaxis={'categoryorder': 'total ascending'})
fig.show()
fig.write_html('story2_categories.html')
print('✅ Chart saved')

"""---
## Story 3: The Nutrient Matrix Visualization 📊
**Goal:** Scatter plot of Sugar vs Protein to identify the "Empty Quadrant" (High Protein + Low Sugar).
"""

# ─────────────────────────────────────────────────────────────
# Step 3a: Compute quadrant thresholds (median split)
# ─────────────────────────────────────────────────────────────
sugar_median   = df['sugars_100g'].median()
protein_median = df['proteins_100g'].median()

print(f'Sugar median:   {sugar_median:.1f}g per 100g')
print(f'Protein median: {protein_median:.1f}g per 100g')

def get_quadrant(row):
    high_sugar   = row['sugars_100g']   >= sugar_median
    high_protein = row['proteins_100g'] >= protein_median
    if high_protein and not high_sugar:
        return '🌟 High Protein / Low Sugar (TARGET)'
    elif high_protein and high_sugar:
        return 'High Protein / High Sugar'
    elif not high_protein and high_sugar:
        return 'Low Protein / High Sugar (CROWDED)'
    else:
        return 'Low Protein / Low Sugar'

df['quadrant'] = df.apply(get_quadrant, axis=1)
print('\nQuadrant distribution:')
print(df['quadrant'].value_counts())

# ─────────────────────────────────────────────────────────────
# Story 3 Main Chart: Sugar vs Protein Scatter
# ─────────────────────────────────────────────────────────────
sample = df.sample(min(8000, len(df)), random_state=42)

quadrant_colors = {
    '🌟 High Protein / Low Sugar (TARGET)': '#2ecc71',
    'High Protein / High Sugar':            '#3498db',
    'Low Protein / High Sugar (CROWDED)':   '#e74c3c',
    'Low Protein / Low Sugar':              '#95a5a6'
}

fig = px.scatter(
    sample,
    x='sugars_100g', y='proteins_100g',
    color='quadrant',
    color_discrete_map=quadrant_colors,
    facet_col='primary_category',
    facet_col_wrap=4,
    opacity=0.5,
    title='🧪 Nutrient Matrix: Sugar vs Protein by Category',
    labels={
        'sugars_100g': 'Sugar (g per 100g)',
        'proteins_100g': 'Protein (g per 100g)'
    },
    hover_data=['product_name', 'brands']
)

# Quadrant lines
fig.add_vline(x=sugar_median,   line_dash='dash', line_color='white', opacity=0.5)
fig.add_hline(y=protein_median, line_dash='dash', line_color='white', opacity=0.5)

fig.update_layout(height=700, paper_bgcolor='rgba(0,0,0,0)')
fig.show()
fig.write_html('story3_nutrient_matrix.html')
print('✅ Saved story3_nutrient_matrix.html')

# ─────────────────────────────────────────────────────────────
# Story 3: By-Category Quadrant Distribution
# ─────────────────────────────────────────────────────────────
quadrant_by_cat = (
    df.groupby(['primary_category', 'quadrant'])
    .size()
    .reset_index(name='count')
)
total_by_cat = df.groupby('primary_category').size().reset_index(name='total')
quadrant_by_cat = quadrant_by_cat.merge(total_by_cat, on='primary_category')
quadrant_by_cat['pct'] = (quadrant_by_cat['count'] / quadrant_by_cat['total'] * 100).round(1)

fig2 = px.bar(
    quadrant_by_cat,
    x='primary_category', y='pct',
    color='quadrant',
    color_discrete_map=quadrant_colors,
    title='📊 Quadrant Distribution by Category (%)',
    labels={'pct': '% Products', 'primary_category': 'Category'},
    text='pct',
    barmode='stack'
)
fig2.update_traces(texttemplate='%{text:.0f}%', textposition='inside')
fig2.update_layout(height=500, xaxis_tickangle=-30)
fig2.show()
fig2.write_html('story3_quadrant_by_category.html')
print('✅ Saved')

"""---
## Story 4: The Market Gap Recommendation 🎯
**Goal:** Identify and quantify the Blue Ocean opportunity.
"""

# ─────────────────────────────────────────────────────────────
# Step 4: Find the "Empty Quadrant" — High Protein, Low Sugar
# ─────────────────────────────────────────────────────────────
target_products = df[df['quadrant'] == '🌟 High Protein / Low Sugar (TARGET)'].copy()
crowded_products = df[df['quadrant'] == 'Low Protein / High Sugar (CROWDED)'].copy()

print('=== Market Gap Analysis ===')
print(f'Total snack products analyzed:    {len(df):,}')
print(f'High Protein / Low Sugar (Gap):   {len(target_products):,} ({len(target_products)/len(df)*100:.1f}%)')
print(f'Low Protein / High Sugar (Crowded): {len(crowded_products):,} ({len(crowded_products)/len(df)*100:.1f}%)')

print('\n=== Target Zone Nutritional Profile ===')
display(target_products[['sugars_100g', 'proteins_100g', 'fat_100g', 'fiber_100g']].describe().round(1))

# Best category for opportunity
gap_by_cat = (
    df.groupby('primary_category')
    .apply(lambda x: (x['quadrant'] == '🌟 High Protein / Low Sugar (TARGET)').mean() * 100)
    .reset_index(name='target_pct')
    .sort_values('target_pct', ascending=False)
)
print('\n=== Target Zone % by Category ===')
display(gap_by_cat)

# ─────────────────────────────────────────────────────────────
# The Recommendation
# ─────────────────────────────────────────────────────────────
best_cat  = gap_by_cat.iloc[0]['primary_category']
gap_pct   = gap_by_cat.iloc[0]['target_pct']

# Target nutritional benchmarks
target_protein = target_products['proteins_100g'].quantile(0.75).round(1)
target_sugar   = target_products['sugars_100g'].quantile(0.25).round(1)

print('=' * 65)
print('              🎯 MARKET RECOMMENDATION FOR HELIX CPG')
print('=' * 65)
print()
print('KEY INSIGHT:')
print(f'"Based on the data, the biggest market opportunity is in')
print(f' {best_cat}, specifically targeting products with')
print(f' {target_protein}g of protein and less than {target_sugar}g of sugar."')
print()
print(f'  • Only {gap_pct:.1f}% of products in this category occupy the')
print(f'    High Protein / Low Sugar quadrant — meaning the market')
print(f'    is severely under-served in this space.')
print()
print(f'  • The "Low Protein / High Sugar" quadrant is over-crowded:')
print(f'    {len(crowded_products)/len(df)*100:.1f}% of all products fall here.')
print('=' * 65)

# ─────────────────────────────────────────────────────────────
# Story 4 Visualization: Market Opportunity Bubble Chart
# ─────────────────────────────────────────────────────────────
opp_data = df.groupby('primary_category').agg(
    avg_sugar   = ('sugars_100g', 'mean'),
    avg_protein = ('proteins_100g', 'mean'),
    product_count = ('product_name', 'count'),
    target_pct  = ('quadrant', lambda x: (x == '🌟 High Protein / Low Sugar (TARGET)').mean() * 100)
).reset_index()

fig = px.scatter(
    opp_data,
    x='avg_sugar', y='avg_protein',
    size='product_count',
    color='target_pct',
    color_continuous_scale='RdYlGn',
    text='primary_category',
    title='🫧 Market Opportunity Map — Category Positioning',
    labels={
        'avg_sugar': 'Avg Sugar (g/100g)',
        'avg_protein': 'Avg Protein (g/100g)',
        'target_pct': '% in Target Zone'
    },
    size_max=60
)
fig.add_vline(x=sugar_median,   line_dash='dash', annotation_text='Sugar Median')
fig.add_hline(y=protein_median, line_dash='dash', annotation_text='Protein Median')

# Shade the target quadrant
fig.add_shape(type='rect',
    x0=0, y0=protein_median, x1=sugar_median, y1=100,
    fillcolor='rgba(46,204,113,0.1)', line_width=0
)
fig.add_annotation(
    x=sugar_median/2, y=protein_median + 5,
    text='🌟 BLUE OCEAN<br>OPPORTUNITY',
    showarrow=False, font=dict(size=11, color='#2ecc71')
)

fig.update_traces(textposition='top center')
fig.update_layout(height=550)
fig.show()
fig.write_html('story4_opportunity_map.html')
print('✅ Saved story4_opportunity_map.html')

"""---
## Bonus: The "Hidden Gem" — Protein Source Ingredients 🔬
**Goal:** Identify the top 3 protein sources in High Protein / Low Sugar products.
"""

# ─────────────────────────────────────────────────────────────
# Extract top protein sources from ingredients_text
# ─────────────────────────────────────────────────────────────
PROTEIN_SOURCES = [
    'whey', 'peanut', 'pea protein', 'soy protein', 'soy',
    'almond', 'cashew', 'chickpea', 'lentil', 'quinoa',
    'egg', 'milk protein', 'casein', 'hemp', 'chia',
    'sunflower seed', 'pumpkin seed', 'sesame', 'flaxseed',
    'brown rice protein', 'oat', 'walnut', 'pistachio'
]

target_with_ingredients = target_products[target_products['ingredients_text'].notna()].copy()
target_with_ingredients['ingredients_lower'] = target_with_ingredients['ingredients_text'].str.lower()

# Count appearances of each protein source
source_counts = {}
for source in PROTEIN_SOURCES:
    count = target_with_ingredients['ingredients_lower'].str.contains(source, regex=False).sum()
    source_counts[source] = count

protein_df = pd.DataFrame(
    sorted(source_counts.items(), key=lambda x: -x[1]),
    columns=['Protein Source', 'Product Count']
)

print('=== Top Protein Sources in High Protein / Low Sugar Products ===')
display(protein_df.head(10))

top3 = protein_df.head(3)['Protein Source'].tolist()
print(f'\n🏆 Top 3 Protein Sources: {top3[0].title()}, {top3[1].title()}, {top3[2].title()}')

# ─────────────────────────────────────────────────────────────
# Bonus Chart: Protein Sources
# ─────────────────────────────────────────────────────────────
fig = px.bar(
    protein_df.head(10),
    x='Product Count', y='Protein Source',
    orientation='h',
    color='Product Count',
    color_continuous_scale='Greens',
    title='🥦 Top Protein Sources in High-Protein / Low-Sugar Products',
    text='Product Count'
)
fig.update_traces(textposition='outside')
fig.update_layout(height=450, yaxis={'categoryorder':'total ascending'}, coloraxis_showscale=False)
fig.show()
fig.write_html('bonus_protein_sources.html')
print('✅ Saved')

"""---
## Candidate's Choice: Nutri-Score vs Market Positioning 🏅

**What it is:** Cross-reference official Nutri-Score grades (A–E) with each product's Sugar/Protein quadrant.

**Why it matters to the business:**  
Regulators in France, Germany, and Belgium now mandate Nutri-Score labels on food products, and more countries are adopting it. A product targeting the High Protein / Low Sugar quadrant must *also* achieve a Nutri-Score of A or B to succeed on retail shelves in these markets. This analysis tells the R&D team what nutritional benchmarks are needed for *both* commercial and regulatory success.
"""

# ─────────────────────────────────────────────────────────────
# Nutri-Score vs Quadrant analysis
# ─────────────────────────────────────────────────────────────
nutri_df = df[df['nutrition_grade_fr'].notna()].copy()
nutri_df['nutrition_grade_fr'] = nutri_df['nutrition_grade_fr'].str.upper().str.strip()
nutri_df = nutri_df[nutri_df['nutrition_grade_fr'].isin(['A', 'B', 'C', 'D', 'E'])]

# Cross-tabulation: Nutri-Score Grade vs Quadrant
cross = pd.crosstab(
    nutri_df['nutrition_grade_fr'],
    nutri_df['quadrant'],
    normalize='index'
) * 100

cross = cross.round(1)
print('=== % of products in each quadrant, by Nutri-Score grade ===')
display(cross)

# Plot
cross_long = cross.reset_index().melt(id_vars='nutrition_grade_fr', var_name='Quadrant', value_name='Pct')

fig = px.bar(
    cross_long,
    x='nutrition_grade_fr', y='Pct',
    color='Quadrant',
    color_discrete_map=quadrant_colors,
    title='🏅 Nutri-Score Grade vs Nutrient Quadrant',
    labels={'nutrition_grade_fr': 'Nutri-Score Grade', 'Pct': '% of Products'},
    barmode='stack',
    text='Pct'
)
fig.update_traces(texttemplate='%{text:.0f}%', textposition='inside')
fig.update_layout(height=500)
fig.show()
fig.write_html('choice_nutriscore.html')
print('✅ Saved choice_nutriscore.html')

# ─────────────────────────────────────────────────────────────
# Export clean data for dashboard
# ─────────────────────────────────────────────────────────────
export_cols = [
    'product_name', 'brands', 'primary_category', 'quadrant',
    'sugars_100g', 'proteins_100g', 'fat_100g', 'fiber_100g',
    'nutrition_grade_fr', 'ingredients_text'
]

clean_export = df[export_cols].copy()
clean_export.to_csv('openfoodfacts_clean.csv', index=False)

opp_data.to_csv('opportunity_map.csv', index=False)
protein_df.to_csv('protein_sources.csv', index=False)

print(f'✅ Exported openfoodfacts_clean.csv — {len(clean_export):,} products')
print('✅ Exported opportunity_map.csv')
print('✅ Exported protein_sources.csv')

print(f'\n=== FINAL SUMMARY ===')
print(f'Products analyzed:          {len(df):,}')
print(f'Categories identified:      {df["primary_category"].nunique()}')
print(f'High Protein / Low Sugar:   {len(target_products):,} ({len(target_products)/len(df)*100:.1f}%)')
print(f'Low Protein / High Sugar:   {len(crowded_products):,} ({len(crowded_products)/len(df)*100:.1f}%)')
print(f'\nTop 3 Protein Sources: {top3}')
print(f'\nRECOMMENDATION: Launch in [{best_cat}]')
print(f'Target: ≥{target_protein}g protein, ≤{target_sugar}g sugar per 100g')