"""
"Sugar Trap" Market Gap Analysis — Interactive Dashboard
AmaliTech Data Engineering Challenge — Project 2
Run: streamlit run project2_dashboard.py
Requires: openfoodfacts_clean.csv, opportunity_map.csv, protein_sources.csv
          (generated by project2_sugar_trap.ipynb)
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import warnings
warnings.filterwarnings("ignore")

# ── Page config ──────────────────────────────────────────────
st.set_page_config(
    page_title="Sugar Trap — Market Gap Analysis",
    page_icon="🥗",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ── Custom CSS ────────────────────────────────────────────────
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;600;700&family=JetBrains+Mono&display=swap');
    html, body, [class*="css"] { font-family: 'Outfit', sans-serif; }
    .kpi-card {
        background: linear-gradient(135deg, #1a1f2e, #242938);
        border: 1px solid #363c55;
        border-radius: 14px;
        padding: 22px 16px;
        text-align: center;
    }
    .kpi-val   { font-size: 2rem; font-weight: 700; }
    .kpi-label { font-size: 0.82rem; color: #8892b0; margin-top: 5px; }
    .insight-box {
        background: linear-gradient(135deg, #0d2818, #0f2e1c);
        border-left: 5px solid #2ecc71;
        border-radius: 10px;
        padding: 18px 22px;
        margin: 10px 0;
        font-size: 1rem;
        line-height: 1.7;
    }
    .rec-box {
        background: linear-gradient(135deg, #1a1228, #201530);
        border: 2px solid #9b59b6;
        border-radius: 14px;
        padding: 22px 28px;
        margin: 16px 0;
        font-size: 1.05rem;
        line-height: 1.8;
    }
    h1, h2, h3 { color: #e8eaf6 !important; }
</style>
""", unsafe_allow_html=True)

# ── Load Data ─────────────────────────────────────────────────
@st.cache_data
def load_data():
    df  = pd.read_csv("openfoodfacts_clean.csv")
    opp = pd.read_csv("opportunity_map.csv")
    pro = pd.read_csv("protein_sources.csv")
    return df, opp, pro

try:
    df, opp_data, protein_df = load_data()
    DATA_LOADED = True
except FileNotFoundError:
    DATA_LOADED = False

# ── Header ────────────────────────────────────────────────────
st.markdown("# 🥗 Sugar Trap — Market Gap Analysis")
st.markdown("**AmaliTech Data Engineering Challenge** | Open Food Facts Dataset | Client: Helix CPG Partners")
st.divider()

if not DATA_LOADED:
    st.error("""
    **CSV files not found.**  
    Please run `project2_sugar_trap.ipynb` first to generate:
    - `openfoodfacts_clean.csv`
    - `opportunity_map.csv`
    - `protein_sources.csv`
    """)
    st.stop()

# ── Constants ─────────────────────────────────────────────────
QUADRANT_COLORS = {
    '🌟 High Protein / Low Sugar (TARGET)': '#2ecc71',
    'High Protein / High Sugar':            '#3498db',
    'Low Protein / High Sugar (CROWDED)':   '#e74c3c',
    'Low Protein / Low Sugar':              '#95a5a6'
}

sugar_median   = df['sugars_100g'].median()
protein_median = df['proteins_100g'].median()

# ── Sidebar ───────────────────────────────────────────────────
st.sidebar.markdown("## 🎛️ Filters")

all_cats = sorted(df["primary_category"].dropna().unique())
selected_cats = st.sidebar.multiselect("Product Category", all_cats, default=all_cats)

sugar_range = st.sidebar.slider(
    "Sugar Range (g/100g)", 0.0, float(df['sugars_100g'].max()), (0.0, float(df['sugars_100g'].max()))
)
protein_range = st.sidebar.slider(
    "Protein Range (g/100g)", 0.0, float(df['proteins_100g'].max()), (0.0, float(df['proteins_100g'].max()))
)

nutri_grades = sorted(df['nutrition_grade_fr'].dropna().unique())
selected_grades = st.sidebar.multiselect("Nutri-Score Grade", nutri_grades, default=nutri_grades)

st.sidebar.divider()
st.sidebar.info(
    "This dashboard identifies the 'Blue Ocean' in the snack market — "
    "product categories where healthy options (High Protein, Low Sugar) are under-served."
)

# ── Apply Filters ─────────────────────────────────────────────
mask = (
    df["primary_category"].isin(selected_cats) &
    df["sugars_100g"].between(*sugar_range) &
    df["proteins_100g"].between(*protein_range)
)
if selected_grades:
    mask &= df["nutrition_grade_fr"].isin(selected_grades) | df["nutrition_grade_fr"].isna()

filtered = df[mask].copy()

# ── KPIs ──────────────────────────────────────────────────────
st.markdown("### 📊 Dataset Overview")
c1, c2, c3, c4, c5 = st.columns(5)

total      = len(filtered)
target_pct = (filtered['quadrant'] == '🌟 High Protein / Low Sugar (TARGET)').mean() * 100
crowded_pct= (filtered['quadrant'] == 'Low Protein / High Sugar (CROWDED)').mean() * 100
avg_sugar  = filtered['sugars_100g'].mean()
avg_protein= filtered['proteins_100g'].mean()

def kpi(col, val, label, color="#a0c4ff"):
    col.markdown(f"""<div class="kpi-card">
        <div class="kpi-val" style="color:{color}">{val}</div>
        <div class="kpi-label">{label}</div>
    </div>""", unsafe_allow_html=True)

kpi(c1, f"{total:,}",          "Products Analyzed",         "#a0c4ff")
kpi(c2, f"{target_pct:.1f}%",  "In Blue Ocean (HP/LS)",     "#2ecc71")
kpi(c3, f"{crowded_pct:.1f}%", "In Crowded Zone (LP/HS)",   "#e74c3c")
kpi(c4, f"{avg_sugar:.1f}g",   "Avg Sugar / 100g",          "#f39c12")
kpi(c5, f"{avg_protein:.1f}g", "Avg Protein / 100g",        "#9b59b6")

st.markdown("<br>", unsafe_allow_html=True)

# ── Row 1: Scatter + Category Bar ─────────────────────────────
st.markdown("### 🧪 Nutrient Matrix — Find the Blue Ocean")

r1c1, r1c2 = st.columns([2, 1])

with r1c1:
    sample = filtered.sample(min(6000, len(filtered)), random_state=42) if len(filtered) > 6000 else filtered
    fig_scatter = px.scatter(
        sample,
        x='sugars_100g', y='proteins_100g',
        color='quadrant',
        color_discrete_map=QUADRANT_COLORS,
        opacity=0.45,
        title="Sugar vs Protein — All Products",
        labels={'sugars_100g': 'Sugar (g/100g)', 'proteins_100g': 'Protein (g/100g)'},
        hover_data=['product_name', 'primary_category', 'brands']
    )
    fig_scatter.add_vline(x=sugar_median,   line_dash="dash", line_color="white", opacity=0.4,
                          annotation_text=f"Sugar Median ({sugar_median:.1f}g)")
    fig_scatter.add_hline(y=protein_median, line_dash="dash", line_color="white", opacity=0.4,
                          annotation_text=f"Protein Median ({protein_median:.1f}g)")
    fig_scatter.add_shape(type='rect',
        x0=0, y0=protein_median, x1=sugar_median, y1=filtered['proteins_100g'].max(),
        fillcolor='rgba(46,204,113,0.08)', line_width=0
    )
    fig_scatter.add_annotation(
        x=sugar_median * 0.3, y=filtered['proteins_100g'].quantile(0.95),
        text="🌟 BLUE OCEAN", showarrow=False,
        font=dict(size=12, color="#2ecc71"), bgcolor="rgba(0,0,0,0.5)"
    )
    fig_scatter.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6", height=480
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

with r1c2:
    quad_counts = filtered['quadrant'].value_counts().reset_index()
    quad_counts.columns = ['Quadrant', 'Count']
    fig_donut = px.pie(
        quad_counts, values='Count', names='Quadrant',
        color='Quadrant', color_discrete_map=QUADRANT_COLORS,
        title="Quadrant Distribution",
        hole=0.5
    )
    fig_donut.update_traces(textinfo='percent+label', textposition='outside')
    fig_donut.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", font_color="#e8eaf6",
        showlegend=False, height=480
    )
    st.plotly_chart(fig_donut, use_container_width=True)

# ── Row 2: Category Deep Dive ──────────────────────────────────
st.markdown("### 📂 Category Deep Dive")

r2c1, r2c2 = st.columns(2)

with r2c1:
    cat_quad = (
        filtered.groupby(['primary_category', 'quadrant'])
        .size().reset_index(name='count')
    )
    fig_stack = px.bar(
        cat_quad, x='primary_category', y='count',
        color='quadrant', color_discrete_map=QUADRANT_COLORS,
        title="Product Distribution by Category & Quadrant",
        labels={'primary_category': 'Category', 'count': 'Products'},
        barmode='stack'
    )
    fig_stack.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6", xaxis_tickangle=-30
    )
    st.plotly_chart(fig_stack, use_container_width=True)

with r2c2:
    opp_filtered = opp_data[opp_data['primary_category'].isin(selected_cats)]
    fig_bubble = px.scatter(
        opp_filtered,
        x='avg_sugar', y='avg_protein',
        size='product_count',
        color='target_pct',
        color_continuous_scale='RdYlGn',
        text='primary_category',
        title="Market Opportunity Map (Bubble = Volume)",
        labels={
            'avg_sugar': 'Avg Sugar (g/100g)',
            'avg_protein': 'Avg Protein (g/100g)',
            'target_pct': '% Target Zone'
        },
        size_max=60
    )
    fig_bubble.add_vline(x=sugar_median,   line_dash="dash", line_color="gray")
    fig_bubble.add_hline(y=protein_median, line_dash="dash", line_color="gray")
    fig_bubble.add_shape(type='rect',
        x0=0, y0=protein_median, x1=sugar_median, y1=opp_data['avg_protein'].max()+5,
        fillcolor='rgba(46,204,113,0.1)', line_width=0
    )
    fig_bubble.update_traces(textposition='top center')
    fig_bubble.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6", height=420
    )
    st.plotly_chart(fig_bubble, use_container_width=True)

# ── Row 3: Nutri-Score + Protein Sources ──────────────────────
st.markdown("### 🏅 Regulatory Lens & Ingredient Insights")

r3c1, r3c2 = st.columns(2)

with r3c1:
    nutri_q = (
        filtered[filtered['nutrition_grade_fr'].notna()]
        .groupby(['nutrition_grade_fr', 'quadrant'])
        .size().reset_index(name='count')
    )
    fig_nutri = px.bar(
        nutri_q,
        x='nutrition_grade_fr', y='count',
        color='quadrant',
        color_discrete_map=QUADRANT_COLORS,
        title="🏅 Nutri-Score Grade vs Nutrient Quadrant",
        labels={'nutrition_grade_fr': 'Nutri-Score Grade', 'count': 'Products'},
        barmode='stack'
    )
    fig_nutri.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6"
    )
    st.plotly_chart(fig_nutri, use_container_width=True)

with r3c2:
    fig_protein = px.bar(
        protein_df.head(10),
        x='Product Count', y='Protein Source',
        orientation='h',
        color='Product Count',
        color_continuous_scale='Greens',
        title="🥦 Top Protein Sources in Blue Ocean Products",
        text='Product Count'
    )
    fig_protein.update_traces(textposition='outside')
    fig_protein.update_layout(
        paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
        font_color="#e8eaf6", yaxis={'categoryorder': 'total ascending'},
        coloraxis_showscale=False
    )
    st.plotly_chart(fig_protein, use_container_width=True)

# ── Key Recommendation ────────────────────────────────────────
st.divider()
st.markdown("### 🎯 Executive Recommendation")

target_products = filtered[filtered['quadrant'] == '🌟 High Protein / Low Sugar (TARGET)']
crowded_products = filtered[filtered['quadrant'] == 'Low Protein / High Sugar (CROWDED)']

# Best category
gap_by_cat = (
    filtered.groupby('primary_category')
    .apply(lambda x: (x['quadrant'] == '🌟 High Protein / Low Sugar (TARGET)').mean() * 100)
    .reset_index(name='target_pct')
    .sort_values('target_pct', ascending=False)
)
best_cat      = gap_by_cat.iloc[0]['primary_category'] if len(gap_by_cat) > 0 else "Protein & Health Bars"
target_protein = target_products['proteins_100g'].quantile(0.75).round(1) if len(target_products) > 0 else 15.0
target_sugar   = target_products['sugars_100g'].quantile(0.25).round(1)   if len(target_products) > 0 else 5.0
top3 = protein_df.head(3)['Protein Source'].str.title().tolist()

col_a, col_b = st.columns(2)

with col_a:
    st.markdown(f"""
    <div class="rec-box">
    <b>📌 KEY INSIGHT (Story 4 Deliverable)</b><br><br>
    <i>"Based on the data, the biggest market opportunity is in 
    <b>{best_cat}</b>, specifically targeting products with 
    <b>{target_protein}g of protein</b> and less than 
    <b>{target_sugar}g of sugar</b> per 100g."</i><br><br>
    Only <b>{target_pct:.1f}%</b> of current products occupy this High Protein / Low Sugar 
    space, while <b>{crowded_pct:.1f}%</b> are clustered in the over-crowded 
    Low Protein / High Sugar zone. This is the Blue Ocean.
    </div>
    """, unsafe_allow_html=True)

with col_b:
    st.markdown(f"""
    <div class="insight-box">
    <b>🔬 R&D Ingredient Brief (Bonus — Hidden Gem)</b><br><br>
    Top 3 protein sources in successful High-Protein / Low-Sugar products:<br><br>
    🥇 <b>{top3[0] if len(top3) > 0 else 'Whey'}</b><br>
    🥈 <b>{top3[1] if len(top3) > 1 else 'Peanut'}</b><br>
    🥉 <b>{top3[2] if len(top3) > 2 else 'Soy Protein'}</b><br><br>
    These ingredients should form the nutritional foundation of the new product line 
    to match what is already resonating with health-conscious consumers.
    </div>
    """, unsafe_allow_html=True)

# ── Product Explorer ──────────────────────────────────────────
st.divider()
st.markdown("### 🔍 Product Explorer — Browse Blue Ocean Products")

blue_ocean = filtered[filtered['quadrant'] == '🌟 High Protein / Low Sugar (TARGET)'].copy()
blue_ocean_display = blue_ocean[[
    'product_name', 'brands', 'primary_category',
    'sugars_100g', 'proteins_100g', 'fat_100g', 'nutrition_grade_fr'
]].rename(columns={
    'product_name': 'Product', 'brands': 'Brand',
    'primary_category': 'Category',
    'sugars_100g': 'Sugar (g)', 'proteins_100g': 'Protein (g)',
    'fat_100g': 'Fat (g)', 'nutrition_grade_fr': 'Nutri-Score'
}).dropna(subset=['Product']).head(100)

st.dataframe(blue_ocean_display, use_container_width=True, height=300)

st.markdown("---")
st.markdown(
    "<center><small>Sugar Trap Market Gap Dashboard · Built with Streamlit & Plotly · "
    "AmaliTech Data Engineering Challenge</small></center>",
    unsafe_allow_html=True
)
